<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>NASA Exoplanet Data Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="exoplanets_files/libs/clipboard/clipboard.min.js"></script>
<script src="exoplanets_files/libs/quarto-html/quarto.js"></script>
<script src="exoplanets_files/libs/quarto-html/popper.min.js"></script>
<script src="exoplanets_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="exoplanets_files/libs/quarto-html/anchor.min.js"></script>
<link href="exoplanets_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="exoplanets_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="exoplanets_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="exoplanets_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="exoplanets_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">NASA Exoplanet Data Analysis</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="cmps530-final-project-robert-biebrich-2023" class="level3">
<h3 class="anchored" data-anchor-id="cmps530-final-project-robert-biebrich-2023">CMPS530 | Final Project | Robert Biebrich | 2023</h3>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction:</h2>
<p>One of the most astounding examples of scientific progress in the last century has been the discovery and successive rapid catalogging of inumerable planets outside our solar system. These planets, called extrasolar planets or exoplanets for short, are alien worlds foreign to us in just about every way imaginable. They orbit distant stars which they call their sun or suns, as many of the systems contain more than one star! Many of them formed in a rather different neighborhood of the galaxy than our own and may hold new and remarkable insights into the nature of the universe we share.</p>
<p>Finding and studying exoplanets can serve two main enterprises, both of which speak to some of the biggest questions we have as a species: First, are we alone in the universe or is there other life out there? Second, is there any other habitable world besides Earth on which, in the far off future, humans might be able to explore and settle? These ideas may sound like science fiction, and for now they are, but modern science and technology have shown us that they are possible and they are worth our efforts to explore.</p>
<p>The table downloaded from the NASA Exoplanet Archive looks like this:</p>
<div class="cell" data-execution_count="203">
<div class="cell-output cell-output-display" data-execution_count="203">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">loc_rowid</th>
<th data-quarto-table-cell-role="th">pl_name</th>
<th data-quarto-table-cell-role="th">hostname</th>
<th data-quarto-table-cell-role="th">sy_snum</th>
<th data-quarto-table-cell-role="th">sy_pnum</th>
<th data-quarto-table-cell-role="th">sy_mnum</th>
<th data-quarto-table-cell-role="th">cb_flag</th>
<th data-quarto-table-cell-role="th">discoverymethod</th>
<th data-quarto-table-cell-role="th">disc_year</th>
<th data-quarto-table-cell-role="th">disc_facility</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">st_lumerr1</th>
<th data-quarto-table-cell-role="th">st_lumerr2</th>
<th data-quarto-table-cell-role="th">st_lumlim</th>
<th data-quarto-table-cell-role="th">st_logg</th>
<th data-quarto-table-cell-role="th">st_loggerr1</th>
<th data-quarto-table-cell-role="th">st_loggerr2</th>
<th data-quarto-table-cell-role="th">st_logglim</th>
<th data-quarto-table-cell-role="th">sy_dist</th>
<th data-quarto-table-cell-role="th">sy_disterr1</th>
<th data-quarto-table-cell-role="th">sy_disterr2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1</td>
<td>11 Com b</td>
<td>11 Com</td>
<td>2</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>Radial Velocity</td>
<td>2007</td>
<td>Xinglong Station</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>93.1846</td>
<td>1.9238</td>
<td>-1.9238</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2</td>
<td>11 Com b</td>
<td>11 Com</td>
<td>2</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>Radial Velocity</td>
<td>2007</td>
<td>Xinglong Station</td>
<td>...</td>
<td>0.071</td>
<td>-0.085</td>
<td>0.0</td>
<td>2.31</td>
<td>0.10</td>
<td>-0.10</td>
<td>0.0</td>
<td>93.1846</td>
<td>1.9238</td>
<td>-1.9238</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>3</td>
<td>11 Com b</td>
<td>11 Com</td>
<td>2</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>Radial Velocity</td>
<td>2007</td>
<td>Xinglong Station</td>
<td>...</td>
<td>0.180</td>
<td>-0.159</td>
<td>0.0</td>
<td>2.45</td>
<td>0.08</td>
<td>-0.08</td>
<td>0.0</td>
<td>93.1846</td>
<td>1.9238</td>
<td>-1.9238</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>4</td>
<td>11 UMi b</td>
<td>11 UMi</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>Radial Velocity</td>
<td>2009</td>
<td>Thueringer Landessternwarte Tautenburg</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>1.93</td>
<td>0.07</td>
<td>-0.07</td>
<td>0.0</td>
<td>125.3210</td>
<td>1.9765</td>
<td>-1.9765</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>5</td>
<td>11 UMi b</td>
<td>11 UMi</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>Radial Velocity</td>
<td>2009</td>
<td>Thueringer Landessternwarte Tautenburg</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>125.3210</td>
<td>1.9765</td>
<td>-1.9765</td>
</tr>
</tbody>
</table>

<p>5 rows × 78 columns</p>
</div>
</div>
</div>
<p>However, many of the planets are listed multiple times, as this database has archived each separate finding of each exoplanet. So for our purposes I am going to group them by name, keeping only the first reported finding of each exoplanet. Our new table, which I will be working with for the rest of the analysis, looks like this:</p>
<div class="cell" data-execution_count="204">
<div class="cell-output cell-output-display" data-execution_count="204">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">pl_name</th>
<th data-quarto-table-cell-role="th">loc_rowid</th>
<th data-quarto-table-cell-role="th">hostname</th>
<th data-quarto-table-cell-role="th">sy_snum</th>
<th data-quarto-table-cell-role="th">sy_pnum</th>
<th data-quarto-table-cell-role="th">sy_mnum</th>
<th data-quarto-table-cell-role="th">cb_flag</th>
<th data-quarto-table-cell-role="th">discoverymethod</th>
<th data-quarto-table-cell-role="th">disc_year</th>
<th data-quarto-table-cell-role="th">disc_facility</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">st_lumerr1</th>
<th data-quarto-table-cell-role="th">st_lumerr2</th>
<th data-quarto-table-cell-role="th">st_lumlim</th>
<th data-quarto-table-cell-role="th">st_logg</th>
<th data-quarto-table-cell-role="th">st_loggerr1</th>
<th data-quarto-table-cell-role="th">st_loggerr2</th>
<th data-quarto-table-cell-role="th">st_logglim</th>
<th data-quarto-table-cell-role="th">sy_dist</th>
<th data-quarto-table-cell-role="th">sy_disterr1</th>
<th data-quarto-table-cell-role="th">sy_disterr2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>11 Com b</td>
<td>1</td>
<td>11 Com</td>
<td>2</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>Radial Velocity</td>
<td>2007</td>
<td>Xinglong Station</td>
<td>...</td>
<td>0.071</td>
<td>-0.085</td>
<td>0.0</td>
<td>2.31</td>
<td>0.10</td>
<td>-0.10</td>
<td>0.0</td>
<td>93.1846</td>
<td>1.9238</td>
<td>-1.9238</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>11 UMi b</td>
<td>4</td>
<td>11 UMi</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>Radial Velocity</td>
<td>2009</td>
<td>Thueringer Landessternwarte Tautenburg</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>1.93</td>
<td>0.07</td>
<td>-0.07</td>
<td>0.0</td>
<td>125.3210</td>
<td>1.9765</td>
<td>-1.9765</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>14 And b</td>
<td>7</td>
<td>14 And</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>Radial Velocity</td>
<td>2008</td>
<td>Okayama Astrophysical Observatory</td>
<td>...</td>
<td>0.081</td>
<td>-0.050</td>
<td>0.0</td>
<td>2.55</td>
<td>0.06</td>
<td>-0.07</td>
<td>0.0</td>
<td>75.4392</td>
<td>0.7140</td>
<td>-0.7140</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>14 Her b</td>
<td>10</td>
<td>14 Her</td>
<td>1</td>
<td>2</td>
<td>0</td>
<td>0</td>
<td>Radial Velocity</td>
<td>2002</td>
<td>W. M. Keck Observatory</td>
<td>...</td>
<td>0.012</td>
<td>-0.010</td>
<td>0.0</td>
<td>4.40</td>
<td>0.09</td>
<td>-0.09</td>
<td>0.0</td>
<td>17.9323</td>
<td>0.0073</td>
<td>-0.0073</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>16 Cyg B b</td>
<td>18</td>
<td>16 Cyg B</td>
<td>3</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>Radial Velocity</td>
<td>1996</td>
<td>Multiple Observatories</td>
<td>...</td>
<td>0.009</td>
<td>-0.013</td>
<td>0.0</td>
<td>4.30</td>
<td>0.03</td>
<td>-0.03</td>
<td>0.0</td>
<td>21.1397</td>
<td>0.0110</td>
<td>-0.0111</td>
</tr>
</tbody>
</table>

<p>5 rows × 78 columns</p>
</div>
</div>
</div>
</section>
<section id="methods" class="level2">
<h2 class="anchored" data-anchor-id="methods">Methods:</h2>
<p>In order to address the big questions I’ve posed in the introduction, I will be employing the help of numerous modules. I have imported and cleaned the data (originally a .csv file) using <code>pandas</code>. Most of the visualizations (such as bar graphs and scatter plots) are done using <code>matplotlib</code>. Interpolation was done in <code>scipy</code> and calculations were aided by <code>numpy</code>. Constants such as <strong>pi</strong> and the <strong>gravitational constant</strong> were also provided by <code>scipy</code>.</p>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results:</h2>
<p>In order to find exoplanets, both in our search for life and our quest for new homes among the stars, it would serve us well to cast a wide net. There are hundreds of billions of stars in our galaxy, the Milky Way! While we can only glimpse a small fraction of those with modern technology, it is nonetheless worth it to figure out what our most effective methods are, and invest in those to maximize our succeess and further our search.</p>
<div class="cell" data-execution_count="205">
<div class="cell-output cell-output-display" data-execution_count="205">
<pre><code>discoverymethod
Transit            4146
Radial Velocity    1071
Microlensing        204
Name: pl_name, dtype: int64</code></pre>
</div>
</div>
<div class="cell" data-execution_count="206">
<div class="cell-output cell-output-display" data-execution_count="206">
<pre><code>97.55263631455821</code></pre>
</div>
</div>
<p>We’ll only take a look at the top 3 methods since a quick calculation can tell us that these methods are responsible for 97.55% of all the discoveries: * <strong>Transit</strong> - this method is by far the most fruitful, nearly 4 times as many discoveries as the next most successful method. The transit method entails carefully observing the same star for a while and looking for preiodic dips in its brightness. These dips are caused by a planet passing in front of the star. The magnitude of the dip tells us the size of the planet and the period between the dips can tell us about the planet’s orbit. * <strong>Radial Velocity</strong> - coming in at a strong second, the radial velocity or Doppler method. This method looks for shifts in starlight that occur if a star is wobbling. These wobbles, if detected are the result of a planet whose gravity is tugging on the star, making small changes to its radial velocity. * <strong>Microlensing</strong> - our third most successful method is called gravitational microlensing. Without drilling to bedrock on the topic of Einstein’s General Relativty, the microlensing method exploits a gravity’s ability to bend light. Some high mass objects (such as large stars or black holes) have such strong gravity that the light from stars behind them appears magnified as if by a lens. This is called gravitational lensing and it can make it easier for our space telescopes to spot exoplanets.</p>
<div class="cell" data-execution_count="207">
<div class="cell-output cell-output-display">
<p><img src="exoplanets_files/figure-html/cell-7-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>Well now that we know what methods will aid us in our quest for habitable exoplanets, lets take a look at what technologies have been most successful at employing these methods…</p>
<div class="cell" data-execution_count="208">
<div class="cell-output cell-output-display" data-execution_count="208">
<pre><code>disc_instrument
Kepler CCD Array        3326
TESS CCD Array           410
Multiple Instruments     329
HARPS Spectrograph       220
HIRES Spectrometer       176
Name: pl_name, dtype: int64</code></pre>
</div>
</div>
<div class="cell" data-execution_count="209">
<div class="cell-output cell-output-display">
<p><img src="exoplanets_files/figure-html/cell-9-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>It’s clear from this chart that NASA’s Kepler spacecraft is high and above the breadwinner when it comes to exoplanet discoveries. Given what we’ve already established, it won’t surprise you to learn that Kepler’s primary method of exoplanet detection is the transit method. While none of the other instruments come close to Kepler’s numbers, it is worth noting that the top two (NASA’s TESS being the second) are both spacecraft. Now we not only have a good idea of what methods are most prolific, but also what technologies we should invest in to best carry out these methods.</p>
<p>Happily, the smart people at NASA, ESA, and other space agencies know this and are making preciesely those investments. This raises the question: how many exoplanets can we expect to discover down the line? Let’s exclude the possiblity that we may invent new methods which could greatly increase the rate and scope of exoplanet discovery, and base our prediction on the current rates of discovery.</p>
<div class="cell" data-execution_count="210">
<div class="cell-output cell-output-display">
<p><img src="exoplanets_files/figure-html/cell-10-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>Here we can see the trend of exoplanet discoveries over the last few decades. At first glance you might think this looks far too chaotic to give us a nice extrapolation into the future. But if we look closer, we can see that the offending irregularities are really just two major spikes in the years 2014 and 2016.</p>
<div class="cell" data-execution_count="211">
<div class="cell-output cell-output-display" data-execution_count="211">
<pre><code>disc_year
2016    1517
2014     875
2021     526
2022     365
2018     324
Name: pl_name, dtype: int64</code></pre>
</div>
</div>
<p>Why might that be? An obvious guess might be that these could be years when a new space telescope was launched. However, Kepler was launched in 2009 and TESS was not until 2018. We know from previous analysis that Kepler is the only instrument with enough discoveries under its belt to cause spikes of this size, but perhaps its data was being released in waves and that is messing with our rate of discovery. Let’s take another look, isolating Kepler this time…</p>
<div class="cell" data-execution_count="212">
<div class="cell-output cell-output-display">
<p><img src="exoplanets_files/figure-html/cell-12-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>It is clear from this chart (which shows Kepler’s discoveries stacked <em>on top</em> of those of all the other instruments) that Kepler is indeed reponsible for the spikes, and that, despite being operational for almost 10 years, nearly all of its discoveries are clumped into only 2 years. We are forced to conclude that the release of Kepler’s discoveries and the actual date those discoveries were made are treated as the same by this databse, even when they almost surely are not. This hypothesis is supported by the fact that the data show Kepler making discoveries up until the present, when in reality it was retired in 2018. Since these artifical dates are unhelpful to the predictions we are trying to make, let’s disregard Kepler’s data for now. The resulting graph looks like this:</p>
<div class="cell" data-execution_count="213">
<div class="cell-output cell-output-display">
<p><img src="exoplanets_files/figure-html/cell-13-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>That’s certainly an improvement! Now let’s extrapolate this into the future. How many exoplanets will we discover 5 years from now? What about 10? 50? 100?</p>
<div class="cell" data-execution_count="214">
<div class="cell-output cell-output-display">
<p><img src="exoplanets_files/figure-html/cell-14-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>While these graphs are far from a complete predictive model, they serve as nice illustrations for what the future of exoplanet discovery may look like. As long as funding continues, the future of exoplanet exploration appears to be bright. And that’s a very good thing, as we will need to assess as many planets as possible in our search for alien life and in order to have chance at finding an Earthlike world.</p>
<p>Both of the main questions we are investigating are best answered in part by searching for planets we deem habitable for life. This search requires us to define criteria for what conditions we beleive are necessary for a planet to give rise to and sustain life. These criteria are of course based entirely on Earth life, as it is the only kind of life we know of. And while it is easy to imagine that alien life may have rather different attributes and therefore require rather different conditions, we have to narrow our search somehow. So looking for framiliar kinds of life seems like a practical place to start.</p>
<p>The first thing we will be checking is the planets’ <strong>density</strong>. This is important because not every planet has a terrestrial surface. Massive gaseous worlds called gas giants (like Jupiter and Saturn) and ice giants (like Uranus and Neptune) consist entirely of vast swirling cloudscapes and possible liquid metal cores. These are certainly no place for humans to settle and not a compelling candidate for housing even the strangest imaginable alien life. These worlds are characterized by their low density, while terrestrial planets (planets with rocky surfaces like Mercury, Venus, Earth, and Mars) have a higher density. While density is not included in the data table, we can easily calculate it with what data we do have. The formula for density (<span class="math inline">\(D\)</span>) is:</p>
<section id="d-m-over-v" class="level4">
<h4 class="anchored" data-anchor-id="d-m-over-v"><span class="math display">\[ D= {m \over V} \]</span></h4>
<p>Where <span class="math inline">\(m\)</span> is the planets <strong>mass</strong> and <span class="math inline">\(V\)</span> is its <strong>volume</strong>. However, we don’t have volume either. Luckily, thanks to the pulling and squeezing of gravity, all planets are the same shape: a sphere (in fact, having accumalated enough mass to compact yourself into a sphere is one of the criteria for being classified as a planet!). So we need only apply the equation for the volume of a sphere:</p>
</section>
<section id="v-4-over-3-pi-r3" class="level4">
<h4 class="anchored" data-anchor-id="v-4-over-3-pi-r3"><span class="math display">\[ V = {4 \over 3} \pi r^3 \]</span></h4>
<p>Each exoplanet’s radius is stored in the database with the units “Earth Radius”. That means we are measuring the exoplanets’ radii by how many Earth radii they contain. That is going to make our units pretty clunky when we get to the density calculation so let’s convert that to the SI units for distance, meters. To do this, we can just take the radius of the exoplanet (let’s call that <span class="math inline">\(r_p\)</span>) in Earth radii and multiply it by the radius of Earth (let’s call that <span class="math inline">\(r_E\)</span>) in meters (6378 km).</p>
</section>
<section id="r_pr_e" class="level4">
<h4 class="anchored" data-anchor-id="r_pr_e"><span class="math display">\[ r_pr_E \]</span></h4>
<p><span class="math display">\[ r_E = 6378\ km \]</span></p>
<p>When we get to the density calculation, we will arrive at a similar problem with the exoplanet’s mass. This is measured in “Earth Mass” in the database, but we will just apply the same fix as above, taking the exoplanet’s mass as <span class="math inline">\(m_p\)</span> and Earth’s mass as <span class="math inline">\(m_E\)</span>:</p>
</section>
<section id="m_pm_e" class="level4">
<h4 class="anchored" data-anchor-id="m_pm_e"><span class="math display">\[ m_pm_E \]</span></h4>
<p><span class="math display">\[ m_E = 5.9722 \times 10^{24}kg \]</span></p>
<p>So to recap, we are calculating exoplanet densities, and in order to do that we must calculate their volumes, and in order to do that we must convert their radii to SI units. I will be writing a function to do this, but it can be represented mathematically by the following equation:</p>
</section>
<section id="d-m_pm_e-over-4-over-3-pi-r_pr_e3" class="level4">
<h4 class="anchored" data-anchor-id="d-m_pm_e-over-4-over-3-pi-r_pr_e3"><span class="math display">\[ D = {m_pm_E \over {4 \over 3} \pi (r_pr_E)^3} \]</span></h4>
<div class="cell" data-execution_count="215">
<div class="cell-output cell-output-display" data-execution_count="215">
<pre><code>7      3403.111841
13    30498.945485
14     5795.107797
30     6297.248301
47     1508.790882
Name: pl_density, dtype: float64</code></pre>
</div>
</div>
<p>We can check our volume and density calculations by testing them out on Earth.</p>
<div class="cell" data-execution_count="216">
<div class="cell-output cell-output-stdout">
<pre><code>Earth's volume in m^3: 1.0826577771020533e+21
Earth's density in kg/m^3: 5516.239874049369</code></pre>
</div>
</div>
<p>According to NASA, Earth has a volume of $ 1.083 ^{21}&nbsp; m^3 $ and a density of $ 5514&nbsp;kg/m^3 $, both of which agree with our calculations.</p>
<p>Now we have the densities of each exoplanet (excluding those whose radius or mass were not available) in units of kilograms per cubic meter (kg/m<sup>3</sup>). To define our cut-off for what density should be the minimum for a habitable world, we must again refer to the only celestial bodies that we can study thoroughly. In our solar system, the least dense terrestrial planet is Mars at 3934 kg/m<sup>3</sup>, while the densest gas giant is Neptune at 1638 kg/m<sup>3</sup>. So we know our cut-off should be somewhere between the two, but that’s a wide margin. For a larger sample size, there are plenty of terrestrial moons in the solar system that we can draw from. Our own moon has a mean density of 3340 kg/m<sup>3</sup> with the least dense being Jupiter’s moon Europa at 3000 kg/m<sup>3</sup>. It seems reasonable to take the desnity of the least dense terrestrial object as our cut-off rather than the densest non-terrestrial object, since we are certainly looking for worlds that are much more like Europa than Jupiter.</p>
<div class="cell" data-execution_count="217">
<div class="cell-output cell-output-display" data-execution_count="217">
<pre><code>7      3403.111841
13    30498.945485
14     5795.107797
30     6297.248301
48     4883.107002
Name: pl_density, dtype: float64</code></pre>
</div>
</div>
<div class="cell" data-execution_count="218">
<div class="cell-output cell-output-stdout">
<pre><code>Number of exoplanets with calcuable densities: 4217
Number of exoplanets with densities meeting our criteria: 495
The difference: 3722</code></pre>
</div>
</div>
<p>Well, our search for a habitable world has narrowed things down quite a bit. We’ve gone from 4217 potential worlds (taking only those who had enough data to do the density calculation), to only 495. That’s a lot of low-desnity worlds (3722 to be exact)! Why might there appear to be so many more gas giants than terrestrial planets in the universe, when in our own solar system the two are equally common? Well, it’s possible we are an unusal kind of solar system, but that’s probably not what’s going on here. It seems more likely that we are just finding more gas giant exoplanets by virtue of their size. They tend to have far more mass than terrestrial worlds, making them easily detectable by the radial velocity method, and far more volume, making them easily detectable to the transiting and microlensing methods.</p>
<p>Next, we will examine what is widley considered to be the most important cirterium in the search for life on other planets: distance from the host star. There are many different kinds of stars all with different sizes and spectra. The farther away from its host star a planet is, the weaker the starlight reaching that planet will be. Too close to the sun, and you get a hot, bright world where water evaporates and any atmosphere would be stripped away by solar radiation. Too far, and you get a cold, dark world where any water would be bound up in solid ice, unavailable to parttake in fostering the chemsitry of life. If a planet orbits a star at just the right distance, such that liquid water can exist on its surface, then that planet is said to occupy the <strong>habitable zone</strong> (also charmingly referred to as the <strong>Goldilocks zone</strong>) of its star.</p>
<p>To calculate the boundaries of a star’s habitable zone, we need only know its luminosity (<span class="math inline">\(L_{star}\)</span>). This value can be calculated using a number of finely measured properties and running them through a series of equations, but thankfully for us, the NASA Exoplanet Archive has a column for the luminosity of an exoplanet’s host star. We will use the following equations:</p>
</section>
<section id="r_i-sqrtl_star-over-1.1-r_o-sqrtl_star-over-0.53" class="level4">
<h4 class="anchored" data-anchor-id="r_i-sqrtl_star-over-1.1-r_o-sqrtl_star-over-0.53"><span class="math display">\[ r_i = \sqrt{L_{star} \over 1.1}\ \ \ \ \ \ \ \ \ \ \ r_o = \sqrt{L_{star} \over 0.53}\]</span></h4>
<p>Where <span class="math inline">\(r_i\)</span> is the inner radius or minumum habitable distance from the host star, and <span class="math inline">\(r_o\)</span> is the outer radius or the greatest habitable distance from the host star. Any planet likely to be good a candidate for life or appropriate for human settlement will fall within <span class="math inline">\(r_i\)</span> and <span class="math inline">\(r_o\)</span>. The values in the denomenators of these equations are constants based on our own solar system. As such, the output of the equations will be in Astronomical Units (AU). An AU is equal to the distance of Earth from the Sun: #### <span class="math display">\[ 1\ AU = 1.496 \times 10^{11} meters \]</span></p>
<p>Let’s calculate the boundaries of the habitable zone for each of these distant solar systems.</p>
<div class="cell" data-execution_count="219">
<div class="cell-output cell-output-display" data-execution_count="219">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">inner_rad</th>
<th data-quarto-table-cell-role="th">outer_rad</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1.427967</td>
<td>2.057201</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2</td>
<td>1.293340</td>
<td>1.863249</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3</td>
<td>0.372949</td>
<td>0.537289</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">4</td>
<td>0.296954</td>
<td>0.427807</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">5</td>
<td>1.431465</td>
<td>2.062239</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Now that we have the boundaries of the habitable zone calculated, let’s see which exoplanets lie within their host stars’ habitable zones.</p>
<div class="cell" data-execution_count="220">
<div class="cell-output cell-output-display" data-execution_count="220">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">pl_name</th>
<th data-quarto-table-cell-role="th">loc_rowid</th>
<th data-quarto-table-cell-role="th">hostname</th>
<th data-quarto-table-cell-role="th">sy_snum</th>
<th data-quarto-table-cell-role="th">sy_pnum</th>
<th data-quarto-table-cell-role="th">sy_mnum</th>
<th data-quarto-table-cell-role="th">cb_flag</th>
<th data-quarto-table-cell-role="th">discoverymethod</th>
<th data-quarto-table-cell-role="th">disc_year</th>
<th data-quarto-table-cell-role="th">disc_facility</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">st_logglim</th>
<th data-quarto-table-cell-role="th">sy_dist</th>
<th data-quarto-table-cell-role="th">sy_disterr1</th>
<th data-quarto-table-cell-role="th">sy_disterr2</th>
<th data-quarto-table-cell-role="th">pl_mass_kg</th>
<th data-quarto-table-cell-role="th">pl_r_meters</th>
<th data-quarto-table-cell-role="th">pl_vol</th>
<th data-quarto-table-cell-role="th">pl_density</th>
<th data-quarto-table-cell-role="th">inner_rad</th>
<th data-quarto-table-cell-role="th">outer_rad</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">5</td>
<td>17 Sco b</td>
<td>24</td>
<td>17 Sco</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>Radial Velocity</td>
<td>2020</td>
<td>Lick Observatory</td>
<td>...</td>
<td>0.0</td>
<td>124.9530</td>
<td>2.5900</td>
<td>-2.5900</td>
<td>8.199942e+27</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>1.431465</td>
<td>2.062239</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">9</td>
<td>24 Sex b</td>
<td>34</td>
<td>24 Sex</td>
<td>1</td>
<td>2</td>
<td>0</td>
<td>0</td>
<td>Radial Velocity</td>
<td>2010</td>
<td>Lick Observatory</td>
<td>...</td>
<td>0.0</td>
<td>72.0691</td>
<td>0.6854</td>
<td>-0.6728</td>
<td>3.777178e+27</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>1.028680</td>
<td>1.481967</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">55</td>
<td>BD+20 2457 c</td>
<td>182</td>
<td>BD+20 2457</td>
<td>1</td>
<td>2</td>
<td>0</td>
<td>0</td>
<td>Radial Velocity</td>
<td>2009</td>
<td>McDonald Observatory</td>
<td>...</td>
<td>0.0</td>
<td>1539.7100</td>
<td>189.9250</td>
<td>-189.9250</td>
<td>2.366884e+28</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>1.697592</td>
<td>2.445635</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">57</td>
<td>BD+20 594 b</td>
<td>184</td>
<td>BD+20 594</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>Transit</td>
<td>2016</td>
<td>K2</td>
<td>...</td>
<td>0.0</td>
<td>179.4610</td>
<td>1.2570</td>
<td>-1.2400</td>
<td>9.734686e+25</td>
<td>15003705.0</td>
<td>1.414047e+22</td>
<td>6884.271875</td>
<td>0.225630</td>
<td>0.325054</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">60</td>
<td>BD+48 740 b</td>
<td>189</td>
<td>BD+48 740</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>Radial Velocity</td>
<td>2018</td>
<td>Multiple Observatories</td>
<td>...</td>
<td>0.0</td>
<td>666.5890</td>
<td>21.5335</td>
<td>-21.5335</td>
<td>3.226845e+27</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>1.221028</td>
<td>1.759074</td>
</tr>
</tbody>
</table>

<p>5 rows × 84 columns</p>
</div>
</div>
</div>
<div class="cell" data-execution_count="221">
<div class="cell-output cell-output-stdout">
<pre><code>Number of stars with calcuable habitable zones: 4033
Number of exoplanets within the habitable zone: 176
The difference: 3857</code></pre>
</div>
</div>
<p>As we can see, residing within the habitable zone is a fairly rare property for a planet to have (only 176 planets in the archive got through this filter). It’s again worth noting that one thing skewing this result may be that it is easier to find gas giant exoplanets, which tend to be further from their star, outside of the habitable zone. However, we can’t count on planets we can’t see, so our search for a habitable world grows narrower.</p>
<div class="cell" data-execution_count="222">
<div class="cell-output cell-output-display" data-execution_count="222">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">pl_name</th>
<th data-quarto-table-cell-role="th">loc_rowid</th>
<th data-quarto-table-cell-role="th">hostname</th>
<th data-quarto-table-cell-role="th">sy_snum</th>
<th data-quarto-table-cell-role="th">sy_pnum</th>
<th data-quarto-table-cell-role="th">sy_mnum</th>
<th data-quarto-table-cell-role="th">cb_flag</th>
<th data-quarto-table-cell-role="th">discoverymethod</th>
<th data-quarto-table-cell-role="th">disc_year</th>
<th data-quarto-table-cell-role="th">disc_facility</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">st_logglim</th>
<th data-quarto-table-cell-role="th">sy_dist</th>
<th data-quarto-table-cell-role="th">sy_disterr1</th>
<th data-quarto-table-cell-role="th">sy_disterr2</th>
<th data-quarto-table-cell-role="th">pl_mass_kg</th>
<th data-quarto-table-cell-role="th">pl_r_meters</th>
<th data-quarto-table-cell-role="th">pl_vol</th>
<th data-quarto-table-cell-role="th">pl_density</th>
<th data-quarto-table-cell-role="th">inner_rad</th>
<th data-quarto-table-cell-role="th">outer_rad</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">57</td>
<td>BD+20 594 b</td>
<td>184</td>
<td>BD+20 594</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>Transit</td>
<td>2016</td>
<td>K2</td>
<td>...</td>
<td>0.0</td>
<td>179.461</td>
<td>1.2570</td>
<td>-1.2400</td>
<td>9.734686e+25</td>
<td>15003705.0</td>
<td>1.414047e+22</td>
<td>6884.271875</td>
<td>0.225630</td>
<td>0.325054</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1954</td>
<td>Kepler-10 c</td>
<td>5979</td>
<td>Kepler-10</td>
<td>1</td>
<td>3</td>
<td>0</td>
<td>0</td>
<td>Transit</td>
<td>2011</td>
<td>Kepler</td>
<td>...</td>
<td>0.0</td>
<td>185.506</td>
<td>0.8110</td>
<td>-0.8050</td>
<td>1.027218e+26</td>
<td>14780720.0</td>
<td>1.351933e+22</td>
<td>7598.146019</td>
<td>0.223607</td>
<td>0.322139</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2104</td>
<td>Kepler-11 g</td>
<td>7485</td>
<td>Kepler-11</td>
<td>1</td>
<td>6</td>
<td>0</td>
<td>0</td>
<td>Transit</td>
<td>2010</td>
<td>Kepler</td>
<td>...</td>
<td>0.0</td>
<td>646.346</td>
<td>6.3750</td>
<td>-6.3750</td>
<td>1.500814e+26</td>
<td>21533980.0</td>
<td>4.180626e+22</td>
<td>3589.926286</td>
<td>0.330289</td>
<td>0.475831</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2381</td>
<td>Kepler-131 c</td>
<td>10176</td>
<td>Kepler-131</td>
<td>1</td>
<td>2</td>
<td>0</td>
<td>0</td>
<td>Transit</td>
<td>2014</td>
<td>Kepler</td>
<td>...</td>
<td>0.0</td>
<td>228.678</td>
<td>1.4310</td>
<td>-1.4130</td>
<td>4.927065e+25</td>
<td>5033090.0</td>
<td>5.337925e+20</td>
<td>92303.000292</td>
<td>0.141421</td>
<td>0.203739</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2851</td>
<td>Kepler-1656 b</td>
<td>14328</td>
<td>Kepler-1656</td>
<td>1</td>
<td>2</td>
<td>0</td>
<td>0</td>
<td>Transit</td>
<td>2018</td>
<td>Kepler</td>
<td>...</td>
<td>0.0</td>
<td>185.875</td>
<td>0.8350</td>
<td>-0.8270</td>
<td>2.902489e+26</td>
<td>28478370.0</td>
<td>9.669717e+22</td>
<td>3001.627828</td>
<td>0.138170</td>
<td>0.199054</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3989</td>
<td>Kepler-47 b</td>
<td>25266</td>
<td>Kepler-47</td>
<td>2</td>
<td>3</td>
<td>0</td>
<td>1</td>
<td>Transit</td>
<td>2012</td>
<td>Kepler</td>
<td>...</td>
<td>0.0</td>
<td>1025.020</td>
<td>30.6445</td>
<td>-30.6445</td>
<td>3.798319e+27</td>
<td>19304130.0</td>
<td>3.011751e+22</td>
<td>126116.634664</td>
<td>0.262851</td>
<td>0.378677</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4076</td>
<td>Kepler-53 c</td>
<td>26130</td>
<td>Kepler-53</td>
<td>1</td>
<td>3</td>
<td>0</td>
<td>0</td>
<td>Transit</td>
<td>2012</td>
<td>Kepler</td>
<td>...</td>
<td>0.0</td>
<td>1366.070</td>
<td>65.8100</td>
<td>-60.1300</td>
<td>2.149992e+26</td>
<td>22744470.0</td>
<td>4.926016e+22</td>
<td>4364.565301</td>
<td>0.180907</td>
<td>0.260623</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">4946</td>
<td>TIC 279401253 b</td>
<td>33004</td>
<td>TIC 279401253</td>
<td>1</td>
<td>2</td>
<td>0</td>
<td>0</td>
<td>Transit</td>
<td>2023</td>
<td>Transiting Exoplanet Survey Satellite (TESS)</td>
<td>...</td>
<td>0.0</td>
<td>285.584</td>
<td>2.7900</td>
<td>-2.7380</td>
<td>1.165455e+28</td>
<td>71412539.0</td>
<td>1.524726e+24</td>
<td>7643.699732</td>
<td>0.296954</td>
<td>0.427807</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">5091</td>
<td>TOI-2180 b</td>
<td>33316</td>
<td>TOI-2180</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>Transit</td>
<td>2022</td>
<td>Transiting Exoplanet Survey Satellite (TESS)</td>
<td>...</td>
<td>0.0</td>
<td>116.685</td>
<td>0.2670</td>
<td>-0.2660</td>
<td>5.229361e+27</td>
<td>72126091.0</td>
<td>1.570889e+24</td>
<td>3328.917910</td>
<td>0.607529</td>
<td>0.875236</td>
</tr>
</tbody>
</table>

<p>9 rows × 84 columns</p>
</div>
</div>
</div>
<p>In fact, filtering by our criteria for both density and distance from host star, we are left with only 9 candidates. Let’s order them by distance and see which would be easiest for us to explore closer.</p>
<div class="cell" data-execution_count="223">
<div class="cell-output cell-output-display" data-execution_count="223">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">pl_name</th>
<th data-quarto-table-cell-role="th">loc_rowid</th>
<th data-quarto-table-cell-role="th">hostname</th>
<th data-quarto-table-cell-role="th">sy_snum</th>
<th data-quarto-table-cell-role="th">sy_pnum</th>
<th data-quarto-table-cell-role="th">sy_mnum</th>
<th data-quarto-table-cell-role="th">cb_flag</th>
<th data-quarto-table-cell-role="th">discoverymethod</th>
<th data-quarto-table-cell-role="th">disc_year</th>
<th data-quarto-table-cell-role="th">disc_facility</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">st_logglim</th>
<th data-quarto-table-cell-role="th">sy_dist</th>
<th data-quarto-table-cell-role="th">sy_disterr1</th>
<th data-quarto-table-cell-role="th">sy_disterr2</th>
<th data-quarto-table-cell-role="th">pl_mass_kg</th>
<th data-quarto-table-cell-role="th">pl_r_meters</th>
<th data-quarto-table-cell-role="th">pl_vol</th>
<th data-quarto-table-cell-role="th">pl_density</th>
<th data-quarto-table-cell-role="th">inner_rad</th>
<th data-quarto-table-cell-role="th">outer_rad</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">5091</td>
<td>TOI-2180 b</td>
<td>33316</td>
<td>TOI-2180</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>Transit</td>
<td>2022</td>
<td>Transiting Exoplanet Survey Satellite (TESS)</td>
<td>...</td>
<td>0.0</td>
<td>116.685</td>
<td>0.267</td>
<td>-0.266</td>
<td>5.229361e+27</td>
<td>72126091.0</td>
<td>1.570889e+24</td>
<td>3328.91791</td>
<td>0.607529</td>
<td>0.875236</td>
</tr>
</tbody>
</table>

<p>1 rows × 84 columns</p>
</div>
</div>
</div>
<p>It seems our nearest possibly habitable neighbor is TOI-2180 b! Though 116.685 parsecs away is nobody’s idea of close. It’s appraoximately 3 quadrillion kilometers away! At this point, our efforts to find life or sanctuary on other worlds may seem hopeless. But really this result is better evidence of the crudeness of our approach…</p>
</section>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<p>For one, we used density to characterize whether or not a planet was a gaseous or terrestrial. This is not an ill-informed strategy, but it is definitely imperfect. Additionally, both the atmosphere and magnetic field of a planet can stretch the habitable zone by trapping heat (via the greenhouse effect) and shielding off cosmic radiation, respecitvely. Neither are easily detectable given our currrent methods of exoplanet discovery. It is also worth reiterating that it is very likely alien life will not obey our conventional notions of what life is like and where it can survive. On top of all of that, we did not consider our own solar system in this analysis (of course, they are by definition not exoplanets) and many of the most promising candidates for life beyond Earth exist right in our cosmic backyard, on the moons and planets oribting our local star! The search for habitable worlds is only in its infancy. There are countless exoplanets yet to be discovered, and many new amazing things to learn along the way. The answers to some of the most profound questions we can ask, are waiting for us out there, in the vastness of space, speckeled with exoplanets swirling about in their star systems.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<section id="dataset" class="level4">
<h4 class="anchored" data-anchor-id="dataset">Dataset:</h4>
<p>NASA Exoplanet Science Institute. (2023). <em>NASA Exoplanet Archive</em>[Dataset]. National Aeronautics and Space Administration. https://exoplanetarchive.ipac.caltech.edu/cgi-bin/TblView/nph-tblView?app=ExoTbls&amp;config=PS</p>
</section>
<section id="other-information-provided-by" class="level4">
<h4 class="anchored" data-anchor-id="other-information-provided-by">Other Information Provided by:</h4>
<p>NASA Science. (2018). <em>Kepler/ K2</em>. National Aeronautics and Space Administration. https://science.nasa.gov/mission/kepler/</p>
<p>NASA Space Science Data Coordinated Archive. (2023). <em>Earth Fact Sheet</em>. National Aeronautics and Space Administration. https://nssdc.gsfc.nasa.gov/planetary/factsheet/earthfact.html</p>
<p>NASA Space Science Data Coordinated Archive. (2023). <em>Planetary Fact Sheet</em>. National Aeronautics and Space Administration. https://nssdc.gsfc.nasa.gov/planetary/factsheet/</p>
<p>Planetary Biology. (2023). <em>Calculating the Habitable Zone</em>. https://www.planetarybiology.com/calculating_habitable_zone.html</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>